[package]
name = "slowcalc"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A calculator for the Slow Computer"

[dependencies]
slowcore = { path = "../slowcore" }
egui = "0.27"
eframe = "0.27"

[[bin]]
name = "slowcalc"
path = "src/main.rs"
