[package]
name = "credits"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
slowcore = { path = "../slowcore" }
egui.workspace = true
eframe.workspace = true
